project_name: toofan

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

changelog:
  use: github-native

release:
  github:
    owner: vyrx-dev
    name: toofan
  make_latest: false
  prerelease: auto
