project_name: toofan

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

aurs:
  - name: toofan-online-bin
    homepage: "https://github.com/vyrx-dev/toofan/tree/toofan-online"
    description: "A typing TUI with multiplayer racing and AI bots"
    maintainers:
      - "vyrx-dev <dev@vyrx.dev>"
    license: "MIT"
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/toofan-online-bin.git'
    package: |-
      install -Dm755 "./toofan" "${pkgdir}/usr/bin/toofan"
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/toofan/LICENSE"

changelog:
  use: github-native

release:
  github:
    owner: vyrx-dev
    name: toofan
  make_latest: false
  prerelease: auto
